### ISSUE TITLE
Any.do Integration Missing Button

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/track-extension#1799]
#### Relevant integration (if any): Any.do

Any.do

### 🐛 Describe the bug

Even though the button has received permission to appear within Any.do, no Start Timer button appears within the webapp's UI (see screenshot below) 

### Expected behaviour

Button should appear in webapp

### Other details or context

[Reported](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481300034531) by user 

<img width="1679" alt="Screen Shot 2020-07-23 at 10 03 19 AM" src="https://user-images.githubusercontent.com/25573455/88302706-c728f900-cccb-11ea-9dac-31acf4a1f4e9.png">

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309713466)

**Comment by tomcat0090** [comment]
@TheSoloJake @dianetoggl @nunofmn 

Is it possible to close this ticket?

**Comment by TheSoloJake** [comment]
@tomcat0090 Not sure; are you experiencing issues with the integration now?

**Comment by tomcat0090** [comment]
@TheSoloJake 
I saw this problem and created a pull request to resolve it.
And it has already been merged.
If there is no problem now, this issue should be closed.
I wonder who has that authority?

**Comment by TheSoloJake** [comment]
@tomcat0090 That'd be me :) Just wanted to make sure you weren't experiencing any additional issues! 

Closing issue
