### ISSUE TITLE
Can't log in after rebranding using FF

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/track-extension#1837]
* **OS version**: Windows 10
* **Browser version**: Firefox 80.0.1 (64-bit)
* **Extension version**: Version 1.66.3

### 🐛 Describe the bug

I'm not able to log in. The first attempt fails and brings me to the Uh-oh page (old design btw) and then I try again and it tells me the credentials are wrong but I can use them with FF to log into the web app

![login tb ff](https://user-images.githubusercontent.com/36152180/92488103-66f40500-f1ee-11ea-96bc-a0fa6c9cd744.gif)

### Expected behaviour

Should be able to login

### Steps to reproduce

Try logging into the Toggl Track extension on Firefox

### additional info:

One user also reached out about this recently: 

User ID: 5359454
WS ID: 2205286
Plan: Premium Annual
Intercom link: https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/106481302472762

I asked them to try again, maybe it's just me, also I can get to the settings page for the extension where there is an option to log out, I get there via the Add-ons view in Firefox:

![image](https://user-images.githubusercontent.com/36152180/92488393-c81bd880-f1ee-11ea-928b-4e446a096e0b.png)

![image](https://user-images.githubusercontent.com/36152180/92488409-cd792300-f1ee-11ea-810a-ad832a422ff4.png)

**Comment by dpsxp** [comment]
@VeljkoTN we're having some issues with login, I don't think is really on toggl-button side. We'll continue on this after the login problem is fixed.

> log out button does nothing btw

It does, but it seems that there's no UI effect showing that something happened. `You're currently logged in as .`  (without the email)

**Comment by dianetoggl** [comment]
I have a user with the same issue on Chrome 
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/106481304664746)

**Comment by langri-sha** [comment]
Fixed!
