### ISSUE TITLE
Toggl icon no longer showing on GQueues

### ISSUE THREAD

**Issue by dianetoggl** [toggl/track-extension#1869]
* **OS version**: Windows 10
* **Browser version**: Chrome 86
* **Extension version**: 1.66.10

### 🐛 Describe the bug

A user got in touch to report 1.66.10 has removed the GQueues integration. I have tested for myself and cannot see the icon on GQueues.

### Expected behaviour

Toggl icon would appear if integration is enabled.

### Steps to reproduce

Steps to reproduce the behaviour:
1. enable Gqueues integration
2. Icon will not appear

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/106481304729592)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481305499996)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481305549475)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481305553833)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309751722)
