### ISSUE TITLE
Toggl Button doesn't show up on Xero

### ISSUE THREAD

**Issue by Phenome** [toggl/track-extension#1910]
* **OS version**: 
* Windows 10
* **Browser version**: 
* Chrome 88
* **Extension version**: 
* 1.69.0

#### Relevant integration (if any):
https://my.xero.com

### 🐛 Describe the bug
Button doesn't show up, like in [the wiki](https://github.com/toggl/toggl-button/wiki/Where-can-I-find-the-Button%3F#xero).

### Expected behaviour
The button to show up

### Steps to reproduce
1. Go to main Xero dashboard
2. Notice the button missing

**Comment by zdericnina** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2759100/conversations/106481307372163)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481308262307)

**Comment by edtamayo** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/106481308426925)

**Comment by maritoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309701008)

**Comment by maritoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309720079)

Since the PR is already there, maybe we can prioritize and finally get it done?
