### ISSUE TITLE
Taiga has updated their UI so the button no longer shows up 

### ISSUE THREAD

**Issue by nidarasheed** [toggl/track-extension#1929]
* **OS version**: latest macOS
* **Browser version**: latest Chrome
* **Extension version**: 1.69.5

#### Relevant integration (if any):

Taiga

### 🐛 Describe the bug

Taiga updated their UI and the button no longer shows up. 
![image](https://user-images.githubusercontent.com/49634673/111764729-57542800-88c5-11eb-9f0a-b0a5266f9122.png)
![image](https://user-images.githubusercontent.com/49634673/111764742-5a4f1880-88c5-11eb-97a0-ba8591f8daf1.png)

### Expected behaviour

See here: https://github.com/toggl/toggl-button/wiki/Where-can-I-find-the-Button%3F#taiga
### Other details or context

[Case](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/conversation/106481308353853)
[Slack](https://toggl.slack.com/archives/C9LMUPD9T/p1616147118006000)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309204081)

**Comment by VeljkoTN** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/106481309725674)

**Comment by EternallLight** [comment]
We've got a report that the button is interfering with the UI now.
It seems to happen with multiple-line titles or missing titles.

![image](https://user-images.githubusercontent.com/4663690/153175840-ba20a750-70dc-43a2-83b5-3c918d79c2f1.png)
![image](https://user-images.githubusercontent.com/4663690/153175913-e8df52e1-e267-427b-86c0-c78a1c386c18.png)
![image](https://user-images.githubusercontent.com/4663690/153175946-488fbd11-4f7f-49fa-a560-c0cadae45caf.png)
