### ISSUE TITLE
Visual bug - Multiple Toggl button icons appearing in Asana board view.

### ISSUE THREAD

**Issue by nicktoggl** [toggl/track-extension#2014]
Windows 10
Chrome 93.0.4577.82
1.70.4

#### Relevant integration (if any):

https://app.asana.com

### 🐛 Describe the bug
On board view, if you click on the item, it will create a new Toggl button repeatedly. You need to switch to list view and then return to board view, in order for the duplicates to disappear.

<img width="309" alt="git1" src="https://user-images.githubusercontent.com/17441860/135196468-c75d0e67-a7fc-45b6-abfa-57b0ecae592f.png">

<img width="307" alt="git2" src="https://user-images.githubusercontent.com/17441860/135196479-de0702c9-7b66-4041-8424-e966879ff8d6.png">

<img width="305" alt="git3" src="https://user-images.githubusercontent.com/17441860/135196487-a8f54132-1a2f-4ee0-98e2-a6d83b621300.png">

### Expected behaviour

There should only be a single Toggl button icon to click at any time.

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to Asana board view
2. Click on item box, click elsewhere
3. Hover over the box, you'll see multiple Toggl button icons
4. Go to list view and return to board view, duplicates should be gone.

### Other details or context

[Case reference ](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309705385)

**Comment by liisa105** [comment]
In the newest version (2.0.1) no buttons are showing on board views at all, so closing this in favour of [this one](https://github.com/toggl/track-extension/issues/2027) :)
