### ISSUE TITLE
Since the latest update to Version 1.70.7  (Updated September 28, 2021)  the teamwork desk integration no longer works

### ISSUE THREAD

**Issue by lanceadam** [toggl/track-extension#2015]
chrome Version 94.0.4606.61
mac BigSur 11.5.2 (20G95)

url:  *://*.teamwork.com/*

Since the latest update to Version 1.70.7  (Updated September 28, 2021)  the teamwork desk integration no longer works, the start timer button that usually site next to the ticket ID is no longer showing.

This is a similar issue as reported here in 2019: https://github.com/toggl/toggl-button/issues/1479

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309709590)

**Comment by nicktoggl** [comment]
Any update on this?

**Comment by EternallLight** [comment]
@nicktoggl I've checked the integration and it seems that the button is still in place, just with some broken styles. I've submitted a PR to fix styles, here's how the integration looks like now: https://cln.sh/IMS7XD

**Comment by lanceadam** [comment]
@EternallLight thanks for looking into this. I see in your screencast that you are using Teamwork Projects. This does have a css issue.  But this issue relates specifically to Teamwork Desk: https://www.teamwork.com/desk/features/  Are you able to please check this?
