### ISSUE TITLE
Button is not picking task name in Asana

### ISSUE THREAD

**Issue by nidarasheed** [toggl/track-extension#2020]
* **OS version**: 11.6
* **Browser version**: Chrome Version 95.0.4638.69 (Official Build) (x86_64)
* **Extension version**:  1.71.0

#### Relevant integration (if any):

Asana

### 🐛 Describe the bug
Clicking button next to task does not pick task even though matching project and task exist in Track

### Expected behaviour

It should pick task name
 
### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to ...
2. ...

### Other details or context

[Slack](https://toggl.slack.com/archives/C9LMUPD9T/p1637138311372700)
[Case](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481309715568)

**Comment by nidarasheed** [comment]
User updated us with more information 
_I just wanted to complete our conversation to clarify that even opening the task in Asana to start the timer, the task was not pre-selected and that I had to do it manually, at least the first time._

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481309722292)

**Comment by liisa105** [comment]
User wants extension to automatically assign time entry to a Track task when the Asana task+project name match Track's. Extension has never done this, added this to [Productboard](https://toggl.productboard.com/insights/notes/all-notes/notes/20806097) as feature request. Full thread [in Slack](https://toggl.slack.com/archives/C015ZEJ3YKF/p1641205327034000?thread_ts=1640240485.457300&cid=C015ZEJ3YKF).
