### ISSUE TITLE
Zendesk integration not working

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/track-extension#2044]
* **OS version**: reproduced on macOS Monterey 12.1, user reported it on Windows 10
* **Browser version**: 98.0.4758.80 Chrome
* **Extension version**: Version 2.0.3

#### Relevant integration (if any):

The button is no longer showing in Zendesk. Here's how Zendesk looks now: 
<img width="1440" alt="Screenshot 2022-02-03 at 15 08 50" src="https://user-images.githubusercontent.com/36152180/152358739-11075c32-418a-4d5d-b1a4-2d2275de3527.png">

According to the "where can I find the button page" it changed slightly again: https://github.com/toggl/track-extension/wiki/Where-can-I-find-the-Button%3F#zendesk-new-ui

### 🐛 Describe the bug

No button

### Expected behaviour

Yes button

### Steps to reproduce

Enable the integration and open the Zendesk dashboard

**Comment by VeljkoTN** [comment]
[intercom case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/106481309730777)

**Comment by nunofmn** [comment]
Not working properly again: https://toggl.slack.com/archives/C9LMUPD9T/p1653996090218699
