### ISSUE TITLE
fix(zendesk): Fix Zendesk integration

### ISSUE THREAD

**Issue by nicktoggl** [toggl/track-extension#2053]
* **OS version**: 
* **Browser version**: 
* **Extension version**: 

#### Relevant integration (if any):

[https://www.zendesk.com/](https://www.zendesk.com/)

### 🐛 Describe the bug

It appears that the button isn't appearing in Zendesk again

### Expected behaviour

Button to appear in Zendesk

### Other details or context

[](https://toggl.slack.com/archives/C9LMUPD9T/p1646648353030569)

[User Case](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309741558)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481309744158)

**Comment by nicktoggl** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309745932)

**Comment by dianetoggl** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309753624)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309754400)

**Comment by dianetoggl** [comment]
One of this users got in touch

> I managed to get to the bottom of the Toggl button not showing up in our Zendesk account.
>It turns out it was because of the "Agent Workspace > Enable Agent Workspace setting". I have disabled this setting and now >the Toggl button shows correctly:
>https://awsm.sh/MMch2k8rWS1ivQprwVUq
>https://awsm.sh/m0JnWjRMxAUl6NNkq0E9
>It would be great if you could pass on this information to the relevant team on your side so that they can have a look at fixing >this.

**Comment by nidarasheed** [comment]
Suggested the above workaround to the users in this list to see if it helps.

**Comment by nicktoggl** [comment]
[User Intercom](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309753624) "Unfortunately, our team actively uses this feature with Zendesk so we are unable to use the workaround."

**Comment by nidarasheed** [comment]
[Another user reported this workaround did not help ](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481309744158)

**Comment by edtamayo** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309760132)

**Comment by Alissonsz** [comment]
Closed by #2091
