### ISSUE TITLE
JIRA Integration Not Working

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/track-extension#2055]
* **OS version**: macOS (latest)
* **Browser version**: Chrome (latest stable: 99.0.4844.51)
* **Extension version**: 2.0.4

#### Relevant integration (if any):

JIRA (Atlassian) 

### 🐛 Describe the bug

JIRA integration no longer appears in JIRA webapp, regardless of domain approval

### Expected behaviour

JIRA integration should have Toggl button within JIRA webapp 

### Other details or context

User [report](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481309740941)

Slack [convo](https://toggl.slack.com/archives/C8H3UCQ9W/p1646421919017719) with @liisa105

**Comment by TheSoloJake** [comment]
User [report](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/conversation/106481309022823)

**Comment by VeljkoTN** [comment]
https://github.com/toggl/track-extension/issues/2054 - closing that one in favour of this one

**Comment by TheSoloJake** [comment]
...I freakin' searched for an issue before creating this one and didn't see anything, sorry! 🙈

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309742310)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/106481309742020
)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309742321)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309742193)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/conversation/106481309741361)

**Comment by VeljkoTN** [comment]
[case](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309742405)

**Comment by chrisse27** [comment]
With fix #2056 the button does appear again, but the Jira issue key is missing when starting the time tracking.

**Comment by denismullaraj** [comment]
[Case reference (PlayStore Review on Android Mobile App)](https://appfigures.com/reviews/280708827791LpvoOL1pXEgrDtL-wmJqbPw?lang=en)
