### ISSUE TITLE
Project names are not showing in extension

### ISSUE THREAD

**Issue by nidarasheed** [toggl/track-extension#2062]
* **OS version**: macOS 12.2.1 (21D62)
* **Browser version**: Version 99.0.4844.51 (Official Build) (x86_64)
* **Extension version**: 2.0.6

#### Relevant integration (if any):

N/A
### 🐛 Describe the bug

Project names are missing 
![image](https://user-images.githubusercontent.com/49634673/158162088-814c996d-48b0-411c-8119-f7cf4f840235.png)

### Expected behaviour
Project names should be there 

### Steps to reproduce
Not sure how it happened, it was all fine last week and I did a fresh reinstall today after which it stopped 

Steps to reproduce the behaviour:
1. Go to ...
2. ...

### Other details or context

[Slack](https://toggl.slack.com/archives/C9LMUPD9T/p1647256259910959)
[Case](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309743316)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481309742941)

**Comment by vedr4n** [comment]
[Test (ignore)](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/conversation/106481309741055)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309742740)

**Comment by EternallLight** [comment]
Tried with both cases on staging, no result, projects are being displayed. 
@nicktoggl , @nidarasheed could you please ask if they still have this issue?

**Comment by VeljkoTN** [comment]
@EternallLight https://www.loom.com/share/90ff8cf0a90f4d0eb015ddfb529e07b9 - they still have the issue, shared a Loom recording of it
