### ISSUE TITLE
Notion Integration Buggy 

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/track-extension#2078]
* **OS version**: macOS Latest
* **Browser version**: Chrome Latest
* **Extension version**: 2.0.8

#### Relevant integration (if any):

Notion (notion.so)

### 🐛 Describe the bug

In a Notion pop-out page, the Start Timer button appears to "crunch" into the corner of the pop-out (see screenshot): 

<img width="1003" alt="Notion issue" src="https://user-images.githubusercontent.com/25573455/163496488-ef047e7b-aa66-4ee6-ad6e-34697836507f.png">

### Expected behaviour

Even spacing between "Open as page" and "Start Timer" button 

### Steps to reproduce

- Enable Notion integration 
- Open Notion webapp and navigate to a pop-out page
- Ta-daaaah

**Comment by karmicdude** [comment]
+1 from me. This happens when you press the "open" button to quickly edit the page, but when you reload the page by pressing Ctrl-R, for example, the position of the Toggle timer button becomes correct.
