### ISSUE TITLE
Todoist integration issue with new UI for task view

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/track-extension#2080]
* **OS version**: macOS 12.3.1
* **Browser version**: 100.0.4896.127
* **Extension version**: Version 2.0.8

#### Relevant integration (if any):

todoist.com

### 🐛 Describe the bug

When navigating through tasks using the up/down arrow buttons a new Track extension icon appears: https://share.getcloudapp.com/OAu6dRWn

### Expected behavior

The extension icon shouldn't multiply with each press of the arrow buttons. 

### Steps to reproduce

Steps to reproduce the behaviour:

You first need to enable the new task view. You can enable it in Todoist Web under Settings / Advanced / Experimental features.

1. Then, click on a task
2. Use the arrow keys to navigate through tasks or use the "K" and "J" keyboard shortcuts for previous and next. 

### Other details or context

A designed from Todoist reached out to let us know, they want to make sure all partner integrations are working fine before this is out of beta

**Comment by edtamayo** [comment]
[Case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309763395)

**Comment by VeljkoTN** [comment]
No longer reproducable
