### ISSUE TITLE
Gitlab issue ID is missing in title

### ISSUE THREAD

**Issue by markoph** [toggl/track-extension#2083]
* **OS version**: Fedora 35
* **Browser version**: Firefox 100.0 (64-bit)
* **Extension version**: Version 2.0.8

#### Relevant integration (if any):

Gitlab

### 🐛 Describe the bug

GitLab Issue ID is not picked automatically when starting time track from issue detail on gitlab.com. I think it started after I updated browser and extensions around two weeks ago. But I am not sure which version I had before (2.0.6 or 2.0.7).

### Expected behaviour

`project#ID` should be part of the title.

### Steps to reproduce

1. Go to any issue on https://gitlab.com/ (eg. random public issue [gitlab-org/release/docs/-/issues/38](https://gitlab.com/gitlab-org/release/docs/-/issues/38))
2. Click start time
3. Issue ID is missing in title: ![Screenshot from 2022-05-09 09-10-16](https://user-images.githubusercontent.com/6843562/167358414-6fa7ebb1-7aa9-4d5d-af75-38be00142723.png)

**Comment by gerrard-provalido** [comment]
Experiencing the same issue, looking at some of our staffs history it looks to have stopped working on the 4th of May.

This looks to have happened at the same time as a GitLab update so that may have caused it.

**Comment by edtamayo** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/106481309763146)

**Comment by larrybotha** [comment]
It appears GitLab has changed their markup, and the extension is failing to get the issue ID.

The current selectors for the issue ID are here: https://github.com/toggl/track-extension/blob/master/src/content/gitlab.js#L75-L81

It may be more reliable to get the ID out of the URL, as there's a good probability the value following `-/issues` is always the issue ID

@nunofmn I see you're a reviewer on some PRs - if I take on this issue, is there anyone I should @mention to accelerate getting approval?

**Comment by nunofmn** [comment]
Hey! 👋 

Yes, @mention me on the PR and I can try to review it asap. 👍

**Comment by Alissonsz** [comment]
Closed by #2103, thank you @larrybotha!!
