### ISSUE TITLE
JIRA Integration - Task Name No Longer Appearing

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/track-extension#2086]
* **OS version**: N/A
* **Browser version**: Chrome - Latest stable
* **Extension version**: 2.0.8

### 🐛 Describe the bug

When using the browser extension within the JIRA webapp, the JIRA reference number and task name were "ported" onto the running entry. Now, only the reference number appears (no task name) 

### Expected behaviour

Both reference number and task name should appear. 

### Steps to reproduce

1. Enable JIRA permission for browser extension
2. Head to JIRA and start timer on task with both task name and reference number
3. Voila

### Other details or context

Slack [convo](https://toggl.slack.com/archives/C015ZEJ3YKF/p1652353374236469)

**Comment by TheSoloJake** [comment]
Case [reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481309755605) 

Case [reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309755632)

**Comment by edtamayo** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/106481309757339)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481309757755)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309757843)

**Comment by edtamayo** [comment]
[Case](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/106481309760159)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/mentions/conversations/106481309761131)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481309761419)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309761646)

**Comment by edtamayo** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/106481309762195)
