### ISSUE TITLE
Asana board and task view is broken

### ISSUE THREAD

**Issue by nicktoggl** [toggl/track-extension#2114]
MacOs Monterey 12.5
Chrome Version 103.0.5060.134
Extension Version 2.0.16

#### Relevant integration (if any):

Asana - https://app.asana.com

### 🐛 Describe the bug

Previously our Extension worked with the Asana Board view, however it appears to have broken. Asana still works on the list view.

### Expected behaviour

The Toggl extension button should appear on board view.

### Steps to reproduce

Switch into Asana board view, no Toggl button, switch back into List view and it is visible.

Steps to reproduce the behaviour:
As above

### Other details or context

[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309778964)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309778980)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309779034)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309775121)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309779158)

**Comment by edtamayo** [comment]
[Case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309779494)

**Comment by liisvirki** [comment]
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309779589)

**Comment by nicktoggl** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309779736)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309779751)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309779393)

**Comment by vedr4n** [comment]
[Case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/2092037/conversation/106481309779839).

**Comment by liisvirki** [comment]
[Case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/3852123/conversation/106481309779935)

**Comment by liisvirki** [comment]
[Case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/3852123/conversation/106481309779988
)

**Comment by nicktoggl** [comment]
[Case reference ](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309780114)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309780118)

**Comment by liisvirki** [comment]
[Case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309780214)

**Comment by liisvirki** [comment]
[Case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/3852123/conversation/106481309780343)

**Comment by liisvirki** [comment]
[Case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/3852123/conversation/106481309780345)

**Comment by edtamayo** [comment]
[Case ref](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309781177?view=List)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309781687?view=List)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309781570?view=List)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309781573?view=List)

**Comment by Patabugen** [comment]
Hey!

The extension is also not working in Calendar view anymore.

I used to use this every day, is there an idea of timeframe that it may be working again?
