### ISSUE TITLE
Some users still can't see the button in Asana

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/track-extension#2120]
* **OS version**: Windows 10
* **Browser version**: Chrome 104.0.0.0
* **Extension version**: 2.0.17

#### Relevant integration (if any):

https://app.asana.com

### 🐛 Describe the bug

This user doesn't see the button in Asana. We recently fixed this issue but there are a couple of users that still claim they can't see it. This specific user shared the most detail and screenshot, you can find them in [intercom](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/2097020/conversation/106481309775121?view=List). We asked the user to disable all other extensions, we asked them to see their integration settings, to remove the extension and add it back.. nothing helped.

### Expected behaviour

The user should see the button in list and task details view 

### Steps to reproduce

Unable to reproduce

**Comment by vedr4n** [comment]
Another user who claims they can't see Asana. [Intercom](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309786113?view=List).

**Comment by vedr4n** [comment]
[And another](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309787516?view=List).

**Comment by vedr4n** [comment]
Random thought: Is there a chance the users who can't see Asana are using the Asana desktop app?

**Comment by liisa105** [comment]
[This user](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309779158?view=List) seems to have the same problem

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309780343?view=List)
[Case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309783814?view=List)

**Comment by nidarasheed** [comment]
@vedr4n One user sent us webapp screenshots.

**Comment by VeljkoTN** [comment]
@nunofmn The button is not showing in the task details view when users change their language in "my settings" in the Asana web app, it works in English only

**Comment by VeljkoTN** [comment]
connected issue #2124

**Comment by VeljkoTN** [comment]
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/2097020/conversation/106481309792848?view=List)

**Comment by VeljkoTN** [comment]
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309795482?view=List)
