### ISSUE TITLE
Button not showing in Task view of Asana when language is set to Japanese 

### ISSUE THREAD

**Issue by nidarasheed** [toggl/track-extension#2124]
* **OS version**: macOS: 12.1
* **Browser version**: Google Chrome
Version: 105.0.5195.125 (Official Build) (arm64)
* **Extension version**: 2.0.17

#### Relevant integration (if any):

Asana
### 🐛 Describe the bug

When language is set to Japanese, the button doesnt show in Task 
![image](https://user-images.githubusercontent.com/49634673/193767863-fb69002b-4822-4bdc-a711-ee55e2103ad6.png)

### Expected behaviour

Button should show, it used to before. 

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to Asana
2. Change language to Japanese
3. Button will not show in Task 

### Other details or context

[Case](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309793054?view=List)
[Case](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309793073?view=List)

**Comment by KevinCassier** [comment]
Hello, 

I don't think it's because of the language. Because I have the same problem in French, English,... since more than one month.

And the button on the left, is not well linked anymore to the projects.

**Comment by dianetoggl** [comment]
[Case ref - spanish user](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309775121?view=List)

> I can see the toggl button in Asana in list and tasks view.. but disappeared in Calenda view.
