### ISSUE TITLE
Include the GH issue number in the time entry

### ISSUE THREAD

**Issue by MarkBennett** [toggl/track-extension#2146]
### Describe the new feature
Our issue titles on GH sometimes change as issues are triaged and understood better. Ideally, the [getPaneDescription()](https://github.com/toggl/track-extension/blob/master/src/content/github.js#L9) function in the GH integration would also pull the issue number.

Happy to submit a PR with this fix if you give me the 👍🏼.

### How does this help you?
We try to tie all our time entries back to an issue to make reporting to the client easier. Automatically picking up the number would make that much easier.

### If we couldn't add this feature, is there a compromise you can think of?
We can manually edit the time entries to add the number, but why? This is what computers are good at!

**Comment by nunofmn** [comment]
Hey @MarkBennett! 👋 

The GH issue number should already be added to the description. 🤔 
But, I noticed that currently there is an issue with picking up the title of the issue in Github Projects boards. I'm going to fix it and release it. I hope that it will also fix the problem you are having. 😅 

Expect it to be available in ~24h.

**Comment by MarkBennett** [comment]
Thanks @nunofmn! Looking forward to checking it out! 😄
