### ISSUE TITLE
Button missing from Google Calendar

### ISSUE THREAD

**Issue by nidarasheed** [toggl/track-extension#2148]
* **OS version**: 
* **Browser version**: 
* **Extension version**: 

#### Relevant integration (if any):

Google Calendar 

### 🐛 Describe the bug

The button is not visible in Calendar events 

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to ...
2. ...

### Other details or context

[Case](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828749?view=List)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828790?view=List)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309828032?view=List)

**Comment by AdrianBou** [comment]
The Google Calendar has changed the names of styles and structure so the extension cannot find the close button
In the code of the track-extension/src/content/google-calendar.js file:
const notTogglPseudoClass = ':not(.toggl)';
const popupDialogSelector = 'div[data-chips-dialog="true"]';
const detailContainerSelector = 'div[data-is-create="false"]';
const rootLevelSelectors = [
  `${popupDialogSelector}`,
  `${detailContainerSelector}${notTogglPseudoClass}`
].join(',');
...
const closeButton = $('[aria-label]:last-child', elem);

The selector that ends up returning in the case of the modal is not the one to close but the one with the three vertical dots
As a first step, replace **"[aria-label]:last-child"** with **"[aria-label]:first-child"**

In addition to the **"target =
       closeButton.parentElement.nextElementSibling.lastElementChild
         .lastElementChild;"** is no longer viable and would have to be rethought

**Comment by TheSoloJake** [comment]
[Report](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/2137598/conversation/106481309827994?view=List)

**Comment by TheSoloJake** [comment]
[Report](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309829022?view=List)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309829096?view=List)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309829162?view=List)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309829170?view=List)

**Comment by TheSoloJake** [comment]
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/2137598/conversation/106481309829274?view=List)

**Comment by edtamayo** [comment]
[Case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309829311)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/2137598/conversation/106481309829322?view=List)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/2137598/conversation/106481309829223?view=List)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/2137598/conversation/106481309829271?view=List)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309829376?view=List)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309829465?view=List)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/2137598/conversation/106481309829489?view=List)

**Comment by edtamayo** [comment]
[Case](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309829773?view=List)

**Comment by edtamayo** [comment]
[Case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309829816)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/2137598/conversation/106481309829834?view=List)

**Comment by nunofmn** [comment]
Thanks @AdrianBou.
Your comment helped us fix the problem faster! 🙌 

PR open #2150 👌
