### ISSUE TITLE
Jira integration stopped working

### ISSUE THREAD

**Issue by whaaaley** [toggl/track-extension#2168]
* **OS version**: Win11
* **Browser version**: Chrome Version 109.0.5414.121 (Official Build) (64-bit)
* **Extension version**: Version 2.0.20

#### Relevant integration (if any):

This was working yesterday, monday, 2/14/2023, but as of this morning is no longer working at all.

### 🐛 Describe the bug

When clicking "start timer" on jira the dropdown no longer appears. I double checked that my integration wasn't disabled.
![image](https://user-images.githubusercontent.com/7419947/219092452-3b9a3621-0a90-48ad-aa26-ddf4d86eff7f.png)

### Expected behaviour

Dropdown, as usual

### Steps to reproduce

1. Jira
2. Click start timer

**Comment by whaaaley** [comment]
It's fixed!

**Comment by kmgalanakis-sage** [comment]
What happens with a custom Jira instance? I can't see the timer anywhere.

**Comment by pabloxio** [comment]
I can't see the time either for a custom Jira instance
