### ISSUE TITLE
ClickUp added a space between '#' and task ID breaking the integration and button missing in sidebar mode

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/track-extension#2170]
* **OS version**: OS X 10.15.7
* **Browser version**: 110.0.0.0
* **Extension version**: 2.0.20

#### Relevant integration (if any):

ClickUp - clickup.com

### 🐛 Describe the bug

From a user:

> I'm using the chrome extension to track time on the listed integration "ClickUp - clickup.com". Recently time entry description has change format slightly and makes the api-sync back to clickup not work.
> 
> the chrome extension used to log all the tracked issues with a hashtag and the ID of the issue, like "#865bpq4t9". The problem is that it is now inserting a space between the hashtag and the ID "# 865bpq4t9" which breaks the api-integration to clickup.
> 
> there is also one more issue. In the new clickup task view (recently released), toggle button doesn't show up in sidebarmode.
> 
> can you have a look at this?

### Other details or context

[This slack thread 🔗 ](https://toggl.slack.com/archives/C015ZEJ3YKF/p1675968530158609)

**Comment by VeljkoTN** [comment]
[Intercom 🔗 ](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309838010?view=List)

**Comment by dianetoggl** [comment]
[Case ref](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/3540765/conversation/106481309838010?view=List)
Clickup shows two buttons now after update
