### ISSUE TITLE
Extension icon is wrong color when you open browser 

### ISSUE THREAD

**Issue by nidarasheed** [toggl/track-extension#2199]
* **OS version**: 
* **Browser version**: 
* **Extension version**: 3.0.4

#### Relevant integration (if any):

N/A
### 🐛 Describe the bug

Since updating Toggl for Chrome (3.0.4), the “light” turns pink by default when I start up Chrome even if I don’t have an active task on the go. It makes me panic every time, thinking I forgot to turn it off and a task is still running! But when I pull it down, it goes grey showing that nothing is running. I’m using Chrome Version 112.0.5615.138 (Official Build) (64-bit)
### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to ...
2. ...

### Other details or context

[Slack](https://toggl.slack.com/archives/C043ZPZQ2JC/p1683199659799559)
[Case 1](https://app.intercom.com/a/inbox/ayixs927/inbox/conversation/106481309863989?view=List)
[Case 2](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309865840?view=List)

**Comment by codeananda** [comment]
Have you enabled all the browser extensions?

**Comment by nidarasheed** [comment]
[case](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309866502?view=List)

**Comment by edtamayo** [comment]
Sharing additional feedback regarding this 🐛 

> Further to this bug report, I also had an experience today where I started a task and when I was finished, it turned out the timer wasn’t keeping track at all. (It was showing as pink in my browser but went grey as soon as I went to stop my work, which was a pretty bad surprise.)

**Comment by nunofmn** [comment]
Fixed in Release v3.0.5.
