### ISSUE TITLE
Fix button's styles in Trello's dark mode 

### ISSUE THREAD

**Issue by nunofmn** [toggl/track-extension#2201]
#### Relevant integration (if any):

- Trello - https://trello.com/

### 🐛 Describe the bug

-When using Trello on dark mode, the button is not visible by default. It's only visible when hovering it.
![Screenshot 2023-05-15 at 18 55 36](https://github.com/toggl/track-extension/assets/1160976/51f1d46b-38e7-4699-85a9-1387e3d4c4b6)

### Expected behaviour

- The button should be visible at all times.

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to Trello (dark mode)
2. The button will not be visible on the task view

### Other details or context
[🧵**Slack thread**](https://toggl.slack.com/archives/C043ZPZQ2JC/p1683798615131769)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309879023?view=List)
