### ISSUE TITLE
Azure DevOps Integration no longer working

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/track-extension#2212]
* **OS version**: Windows 10
* **Browser version**: Opera 99.0.0.0
* **Extension version**: 3.0.7

#### Relevant integration (if any):

VisualStudio / Azure DevOps - azure.com

### 🐛 Describe the bug

> I use Opera, which uses the Chrome extension marketplace. The Toggl extension has recently stopped working in Azure Devops (the start task button does nothing) and today the button has disappeared entirely. I have already tried re-configuring the site list. And I've also uninstalled and re-installed the extension to no avail.

> I have tried a custom URL in conjunction with the pre-loaded template and resetting settings and it did not fix it. The rest of my team are experiencing the same issue. I suspect the HTML structure of the Azure Devops page has changed.

### Expected behavior

The Azure DevOps integration should work :) 

### Steps to reproduce

1. Go to Azure DevOps
2. Start a Free account
3. Enable the integration
4. Notice the button is not visible

[Intercom case
](https://app.intercom.com/a/inbox/ayixs927/inbox/conversation/106481309878352?view=List)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309879023?view=List)

**Comment by nidarasheed** [comment]
[Case](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309878352?view=List)
