### ISSUE TITLE
Extension not picking Asana project name. 

### ISSUE THREAD

**Issue by nidarasheed** [toggl/track-extension#2236]
* **OS version**: 
* **Browser version**: 
* **Extension version**: 3.0.15

#### Relevant integration (if any):

Asana

### 🐛 Describe the bug

When you start a timer in Asana, project is not being picked up (even if matching one exists in Track). 

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to ...
2. ...

### Other details or context
[Case](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309903598?view=List)
[Slack](https://toggl.slack.com/archives/C043ZPZQ2JC/p1692348767058949)

**Comment by edtamayo** [comment]
[Case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/3824737/conversation/106481309907251?view=List)

**Comment by liisvirki** [comment]
[Case ref](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/3852123/conversation/106481309911396?view=List)

**Comment by liisvirki** [comment]
[Case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/3852123/conversation/106481309911949?view=List
)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309920030?view=List)
