### ISSUE TITLE
Remove button from 'New event' on GCal

### ISSUE THREAD

**Issue by nunofmn** [toggl/track-extension#2239]
#### Relevant integration (if any):
- Google Calendar

### 🐛 Describe the bug

- The button is showing up on the 'New event' dialog on Google Calendar:
  - It isn't showing up correctly – wrong styling
  - It doesn't make much sense to have it there, since there isn't any event name to autocomplete the description.

### Expected behaviour
- The button shouldn't show up on the 'New event' dialog

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to Google Calendar
2. Enable the Google Calendar integration on the extension
3. Create a new event on the calendar. The button will show up on the dialog.

**Comment by with-shrey** [comment]
I dont see this as an issue 
Someone who works an an PA might want to track creation on calendar events as a TE :-)
