### ISSUE TITLE
Toggl Track Button disappeared from Trello

### ISSUE THREAD

**Issue by ckamper** [toggl/track-extension#2257]
* **Windows 11**: 
* **Chrome recent**: 
* **recent**: 

#### Relevant integration (if any):

trello.com

### 🐛 Describe the bug

The Toggl Button disappeared from Trello when you open a card.

### Expected behaviour

When I open a card in Trello, there is the Toggl Track button on the right hand side

### Steps to reproduce

use toggl, activate integration with trello, open trello, see no button

### Other details or context

It stopped working on 2023-12-13

**Comment by willrowe** [comment]
It has disappeared for me as well.

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481309954873?view=List)

**Comment by liisvirki** [comment]
[Case reference](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/3852123/conversation/106481309961693?view=List)

**Comment by liisvirki** [comment]
[Case reference ](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/3852123/conversation/106481309966265?view=List)

**Comment by ttsukagoshi** [comment]
Same here:

- Windows 10 build 19045
- Chrome v120.0.6099.130 (latest stable)

For clarity's sake:
Trello being https://trello.com/
and integration for the website enabled:
![Screenshot image of the Integrations section of the settings page for the toggl track extension, with the integration with trello.com being enabled.](https://github.com/toggl/track-extension/assets/55706659/c3e463ba-e405-4225-82f4-37318f93d20a)

I've worked around similar situations by reloading the Trello page with browser cache cleared, but this time the problem doesn't solve itself.

**Comment by ttsukagoshi** [comment]
As a follow-up to my last comment above, the issue has resolved for me.

- I faced the issue when I changed my PC.
- My Chrome browser was synced, so the toggl extension was installed automatically in my new PC browser. The `Integrations` settings in the toggl extension (which users can access via `chrome-extension://<extension-id>/settings.html`) were also reflected on my new browser. The checkbox for trello.com was enabled.
- However, `*://*.trello.com/*` was not among the list of site access permissions for the toggl extension on my new browser (which users can access via `chrome://extensions/?id=<extension-id>`, which was probably the reason why I didn't see the toggl track button on trello.com web pages.

When I un-checked the Integrations checkbox for trello.com and re-checked it, the dialog for Chrome asking me whether to permit toggl extensions access for trello.com appeared. Consenting to this has solved the issue for me.

**Comment by Coffei** [comment]
Still seeing this issue today. If I open a card and then refresh the page the button appears. But when I navigate within the app it no longer appears, so it probably has something to do with the detection of when a card is open and when the button should be added to the page.
