### ISSUE TITLE
We don't grab Notion page titles when it is opened in "side peek"

### ISSUE THREAD

**Issue by izontm** [toggl/track-extension#2260]
🐛 Bug Report
If we fully open and I start the timer from a Notion page, it does grab the title. But if the page (database item) is opened in "side peek" mode, the timer does not grab the title.

Expected behavior
We must get page titles both for full-opened and "side peek" pages.

To reproduce

Open a database item in "side peek"
Start tracking time

## Suggestions
Assuming the URL param `p=ec0aeacacd9c4f5c884e8a15b8d51463`
Is it possible to get the title using the element with `div[data-block-id="ec0aeaca-cd9c-4f5c-884e-8a15b8d51463"] h1`

**Comment by nidarasheed** [comment]
[case](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309945956?view=List)
