### ISSUE TITLE
Button disappeared on YouTrack after their UI updated

### ISSUE THREAD

**Issue by nidarasheed** [toggl/track-extension#2265]
* **OS version**: 
* **Browser version**: 
* **Extension version**: 

#### Relevant integration (if any):
YouTrack

### 🐛 Describe the bug

Button has vanished after UI update. Here is where it used to be 
![image](https://github.com/toggl/track-extension/assets/49634673/91f9fcc2-dead-4732-bf18-48ccb1ce0c01)
[Case](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309973511?view=List)

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to ...
2. ...

**Comment by Datamined** [comment]
Hello, is there any plan to fix Toggl extension integration with Youtrack soon? It highly affects the team management pipeline in our organization (and I do believe in many others too). Is there a way to set kinda bounty for this bug resolution?

**Comment by nidarasheed** [comment]
[case](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481309992517?view=List)
