### ISSUE TITLE
Github - toggl button isn't visible on an issue popup

### ISSUE THREAD

**Issue by cipas** [toggl/track-extension#2269]
* **macOS 13.6.3**:
* **Chrome 120.0.6099.234**: 
* **3.0.29**: 

#### Relevant integration (if any):

https://github.com/

### 🐛 Describe the bug

I cannot start the timer from a issue pop up opened from a project. The button is missing
### Expected behaviour

Toggl button should be visible on top of assignees section in a issue pop-up.
### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to a github project
2. Click on an issue and open a popup

**Comment by rtud** [comment]
Same here: the button is available when the issue is open in a new page, however it doesn't show up for any issue opened within GitHub Projects.
