### ISSUE TITLE
[Bug?]: TickTick appears to be adding extra xxxx at the start of the description.

### ISSUE THREAD

**Issue by askides** [toggl/track-extension#2312]
TickTick appears to be adding extra xxxx at the start of the description. [Case](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481310050221?view=List)

**Comment by qubist-pixel-ux** [comment]
Any progress ?

**Comment by nidarasheed** [comment]
[case](https://app.intercom.com/a/inbox/ayixs927/inbox/admin/534741/conversation/106481310073420?view=List)

**Comment by nidarasheed** [comment]
[Case](https://app.intercom.com/a/inbox/ayixs927/inbox/shared/unassigned/conversation/106481310084271?view=List)
