### ISSUE TITLE
Idle detection limit seems hardcoded to 15 seconds.

### ISSUE THREAD

**Issue by opus-2** [toggl/track-extension#2322]
* **OS version**: Linux Kubuntu 24.04
* **Browser version**: Chrome 127.0.6533.119
* **Extension version**: 4.0.4

#### Relevant integration (if any):
none

### 🐛 Describe the bug
The idle detection time limit seems to be hardcoded to 15 seconds in this version. I've set it to 180 in the extension settings, restarted the whole system to make sure it picked up, and it still shows 180 in the settings, But warns me if I stop working for 15 seconds.

### Expected behaviour

It should act according to the time limit set in the extension options.

### Steps to reproduce

Steps to reproduce the behaviour:
1. Enable idle detection and set it to 100 seconds.
2. Stand still for 20 seconds.
3. Move the mouse.
4. The extension warns you that you have been idle for 5 seconds.

### Other details or context

I've tried login out and back in, restarting chrome, restarting the machine and even reinstalling the extension.

**Comment by with-shrey** [comment]
Closing as already fixed
