### ISSUE TITLE
Timer button in Outlook is misaligned.

### ISSUE THREAD

**Issue by zeel01** [toggl/track-extension#2327]
* **OS version**: Windows 11
* **Browser version**: Chrome 129.0.6668.12
* **Extension version**: 4.0.6

#### Relevant integration (if any):

Outlook (outlook.office.com)

### 🐛 Describe the bug

The timer button is not aligned properly with the toolbar:

![image](https://github.com/user-attachments/assets/7e6b3a77-de07-438c-a09e-be6a629df2a3)

### Expected behaviour

The button should be aligned to the same axis as the other buttons in the toolbar.

### Steps to reproduce

View Outlook with the extension enabled.

### Other details or context

I've just started using the extension for the first time, so I have only ever seen it this way. This may be related to https://github.com/toggl/track-extension/issues/2216 and https://github.com/toggl/track-extension/issues/2167 or already resolved by https://github.com/toggl/track-extension/pull/2291.

Additionally I've never used this integration before so I'm not sure if this is a regression or just something the integration doesn't do... but when I start the timer there is no title given to the time entry. I would expect it to pull the Email title, but it doesn't. Is that also broken, or is that not implemented?

**Comment by pkvach** [comment]
Hi!
Thanks for bringing this up. The issues you mentioned, including the button alignment and the timer not pulling the email title, have been addressed in PR #2291. However, this PR is still awaiting review and hasn't been merged yet. Once it's merged and released, these issues should be resolved.
